In [2]:
import os
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import random
import copy
import matplotlib.colors as c 

In [3]:
# Befehl muss zweimal ausgeführt werden (komisch)
%matplotlib qt
%matplotlib qt
plt.close('all')

In [4]:
path_folder = 'F:/Laederach/Labels/single_bmp/' # Image path
r = [100,125]
rg_variation = [9, 30]
gb_variation = [-70, -50]
variation = 10

In [5]:
path_folder, dirs, files = next(os.walk(path_folder))
number_images = len(files)

print(path_folder)
print(files)
print(number_images)

F:/Laederach/Labels/single_bmp/
['01_20181027_Haselnuss.bmp', '01_20181027_Haselnuss_choco.bmp']
2


In [33]:
with Image.open(path_folder + files[1]) as file:
    img = np.array(file)
    plt.figure(files[1])
    plt.imshow(img/255)

In [7]:
img_binary = img
img_binary[img<255] = 0

In [8]:
plt.figure(files[1] + '_' + 'binary')
plt.imshow(img_binary)

In [9]:
print(np.shape(img_binary))

(266, 380, 3)


In [10]:
def color_label_rgb(img, r, rg_variation, gb_variation, variation):
    
    r_tmp = random.randint(r[0], r[1])
    g_tmp = random.randint(r_tmp + rg_variation[0], r_tmp + rg_variation[1])
    b_tmp = random.randint(g_tmp + gb_variation[0], g_tmp + gb_variation[1])
   
    image_colored = copy.deepcopy(img)
    y,x,z = np.shape(img)
    print(r_tmp, g_tmp, b_tmp)
    
    for i in range(y):
        for j in range(x):
            if img[i,j,0] == 0:
                r_value = random.randint(r_tmp - variation, r_tmp + variation)
                g_value = random.randint(g_tmp - variation, g_tmp + variation)
                b_value = random.randint(b_tmp - variation, b_tmp + variation)
                image_colored[i,j,0] = r_value
                image_colored[i,j,1] = g_value
                image_colored[i,j,2] = b_value
                if i == 0 and j == 0 and z == 0:
                    print(r_value, g_value, b_value)
    
    return image_colored

In [11]:
for i in range(10):
    image_color = color_label_rgb(img_binary, r, rg_variation, gb_variation, variation)
    plt.figure(str(i))
    plt.imshow(image_color)

106 128 68
112 133 74
124 146 79
121 136 76
109 125 75
118 127 60
111 128 67
111 131 73
113 136 72
122 147 85


HSV Wikiepdia: <br>
https://de.wikipedia.org/wiki/HSV-Farbraum <br>
rgb to hsv and hsv to rgb: <br>
https://matplotlib.org/api/_as_gen/matplotlib.colors.rgb_to_hsv.html#matplotlib.colors.rgb_to_hsv <br>

In [29]:
h = 60/360 # gelb = 60
s = 0.9    # Farbsättigung (saturation): (0% = Neutralgrau, 50% = wenig gesättigte Farbe, 100% = gesättigte, reine Farbe), entspricht einem Intervall von Null bis Eins
v = 0.9    # Hellwert (auch Dunkelstufe genannt) (value): (0% = keine Helligkeit, 100% = volle Helligkeit), entspricht einem Intervall von Null bis Eins.
def color_label_hsv(img, h, s, v):
           
    image_colored = c.rgb_to_hsv(copy.deepcopy(img))
    y,x,z = np.shape(img)
    
    for i in range(y):
        for j in range(x):
            if img[i,j,0] == 0:
                image_colored[i,j,0] = h
                image_colored[i,j,1] = s
                image_colored[i,j,2] = v
    
    return image_colored

In [30]:
image_hsv = color_label_hsv(img_binary/255, h, s, v)
# print(np.max(image_hsv), np.min(image_hsv))
image_rgb = c.hsv_to_rgb(image_hsv)
# print(np.max(image_rgb), np.min(image_rgb))

plt.close('all')
plt.figure('saf')
plt.imshow(image_rgb)

In [25]:
plt.close('all')

In [32]:
print(img_binary)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [  0   0   0]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [  0   0   0]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [61]:
type(img_binary)

numpy.ndarray