In [91]:
import os
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import random
import copy
import matplotlib.colors as c 
import time

In [26]:
# Befehl muss zweimal ausgeführt werden (komisch)
%matplotlib qt
%matplotlib qt
plt.close('all')

In [27]:
path_folder = 'C:/Users/User/Desktop/Laederach/Labels/single_bmp/' # Image path
r = [100,125]
rg_variation = [9, 30]
gb_variation = [-70, -50]
variation = 10

In [28]:
path_folder, dirs, files = next(os.walk(path_folder))
number_images = len(files)

print(path_folder)
print(files)
print(number_images)

C:/Users/User/Desktop/Laederach/Labels/single_bmp/
['20181027_Haselnuss.bmp', '20181027_Haselnuss_choco.bmp']
2


In [29]:
with Image.open(path_folder + files[1]) as file:
    img = np.array(file)
    plt.figure(files[1])
    plt.imshow(img/255)

In [30]:
img_binary = img
img_binary[img<255] = 0

In [31]:
plt.figure(files[1] + '_' + 'binary')
plt.imshow(img_binary)

In [32]:
print(np.shape(img_binary))

(266, 380, 3)


In [33]:
def color_label_rgb(img, r, rg_variation, gb_variation, variation):
    
    r_tmp = random.randint(r[0], r[1])
    g_tmp = random.randint(r_tmp + rg_variation[0], r_tmp + rg_variation[1])
    b_tmp = random.randint(g_tmp + gb_variation[0], g_tmp + gb_variation[1])
   
    image_colored = copy.deepcopy(img)
    y,x,z = np.shape(img)
    print(r_tmp, g_tmp, b_tmp)
    
    for i in range(y):
        for j in range(x):
            if img[i,j,0] == 0:
                r_value = random.randint(r_tmp - variation, r_tmp + variation)
                g_value = random.randint(g_tmp - variation, g_tmp + variation)
                b_value = random.randint(b_tmp - variation, b_tmp + variation)
                image_colored[i,j,0] = r_value
                image_colored[i,j,1] = g_value
                image_colored[i,j,2] = b_value
                if i == 0 and j == 0 and z == 0:
                    print(r_value, g_value, b_value)
    
    return image_colored

In [34]:
for i in range(10):
    image_color = color_label_rgb(img_binary, r, rg_variation, gb_variation, variation)
    plt.figure(str(i))
    plt.imshow(image_color)

101 110 57
113 123 53
100 115 64
116 128 72
107 117 50
105 133 81
113 126 73
110 122 58
105 124 58
114 137 83


HSV Wikiepdia: <br>
https://de.wikipedia.org/wiki/HSV-Farbraum <br>
rgb to hsv and hsv to rgb: <br>
https://matplotlib.org/api/_as_gen/matplotlib.colors.rgb_to_hsv.html#matplotlib.colors.rgb_to_hsv <br>

In [35]:
h = 60/360 # gelb = 60
s = 0.9    # Farbsättigung (saturation): (0% = Neutralgrau, 50% = wenig gesättigte Farbe, 100% = gesättigte, reine Farbe), entspricht einem Intervall von Null bis Eins
v = 0.9    # Hellwert (auch Dunkelstufe genannt) (value): (0% = keine Helligkeit, 100% = volle Helligkeit), entspricht einem Intervall von Null bis Eins.
def color_label_hsv(img, h, s, v):
           
    image_colored = c.rgb_to_hsv(copy.deepcopy(img))
    y,x,z = np.shape(img)
    
    for i in range(y):
        for j in range(x):
            if img[i,j,0] == 0:
                image_colored[i,j,0] = h
                image_colored[i,j,1] = s
                image_colored[i,j,2] = v
    
    return image_colored

In [47]:
image_hsv = color_label_hsv(img_binary/255, h, s, v)
# print(np.max(image_hsv), np.min(image_hsv))
image_rgb = c.hsv_to_rgb(image_hsv)
# print(np.max(image_rgb), np.min(image_rgb))

plt.close('all')
plt.figure('image rgb')
plt.imshow(image_rgb)

In [55]:
image_rgb_invert = copy.deepcopy(image_rgb)
image_rgb_invert[img_binary/255==1.0] = 0.0
plt.figure('iamge rgb invert')
plt.imshow(image_rgb_invert)

In [48]:
plt.close('all')

In [38]:
print(img_binary)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [  0   0   0]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [  0   0   0]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [61]:
type(img_binary)

numpy.ndarray

In [68]:
background_folder = 'C:/Users/User/Desktop/Laederach/Labels/Background/' # Background path
background_folder, dirs, files = next(os.walk(background_folder))
number_images = len(files)

print(background_folder)
print(files)
print(number_images)

C:/Users/User/Desktop/Laederach/Labels/Background/
['20181028_blue.bmp', '20181028_blue_brown.bmp', '20181028_blue_brown_white.bmp', '20181028_blue_middle.bmp', '20181028_blue_reflection.bmp', '20181028_blue_white.bmp']
6


In [80]:
# resize ist keine gute Idee schlechte interpolation, besser mehrere Stücke übereinanderlegen
with Image.open(background_folder + files[0]) as file:
    img = np.array(file)
    plt.figure(files[0])
    plt.imshow(img/255)
    
    y, x, z = np.shape(img_binary)
    img_size = file.resize((x, y))
    img_size_array = np.array(img_size)/255

In [81]:
plt.figure(files[0])
plt.imshow(img_size_array)


In [82]:
np.shape(img_binary)

(266, 380, 3)

In [94]:
image_finish = (0.5*image_rgb_invert+2*img_size_array)/2
plt.figure('image finish14')
plt.imshow(image_finish)

In [67]:
plt.close('all')

In [100]:
img_size_uint8 = Image.fromarray(np.uint8(image_finish*255))
img_size_uint8.save('C:/Users/User/Desktop/Laederach/Labels/generated_image/' + time.strftime('%Y%m%d') + '_' + 'try' + '.bmp')